
services:
  postgres:
    image: postgres:15
    container_name: postgres_myapi
    restart: always
    environment:
      POSTGRES_USER: nexa
      POSTGRES_PASSWORD: nexa123
      POSTGRES_DB: task_nexa
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nexa_network

  node_task:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_task
    restart: always
    ports:
      - 8000:8000
    networks:
      - nexa_network


networks:
  nexa_network:
    driver: bridge
    external: true